apiVersion: apps/v1
kind: Deployment
metadata:
  name: myimg
spec:
  replicas: 2   
  selector:
    matchLabels:
      app: myimg
  template:
    metadata:
      labels:
        app: myimg
    spec:
      containers:
      - name: myimg
        image: xphenomenal/myimg:latest  #  
        ports:
        - containerPort: 80   
